name: week_day_picker
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter   
  collection: ^1.16.0
  intl: ^0.17.0
  logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

flutter:

