name: week_day_picker
description: week day picker is a dart package to show a date calandar as a week, targeting all platform, customized Theme and Locale
version: 1.0.0
homepage: https://github.com/MoezAyadiDev/week_day_picker
repository: https://github.com/MoezAyadiDev/week_day_picker

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter   
  collection: ^1.17.0
  intl: ^0.17.0
  # logging: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.3.2

flutter:

